### ISSUE TITLE
Option to specify logger

### ISSUE THREAD

**Issue by ross-w** [WeAreFarmGeek/diplomat#9]
The following line:
https://github.com/WeAreFarmGeek/diplomat/blob/master/lib/diplomat/rest_client.rb#L18
sends all output to STDOUT.

That's all well and good in a Rails app, but when running from a commandline Ruby script this pollutes the output to the terminal. It would be great if there was a way to specify the log output to go elsewhere, or at the very least suppress it entirely.
#### Todo:
- [x] Add Initializer config
- [x] Add option to modify consul URL
- [x] Add option to specify logger
